spring:
  application:
    name: social-media-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/social_media}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG